version: "2"
services:
  rabbitMQ:
    image: openjdk:8
    container_name: rabbitMQ
    network_mode: host
    volumes:
      - "${PWD}/data:/data"
    environment:
      - LANG=ko_KR.euckr
    ports:
      - 5672:5672
      - 15672:15672
